apiVersion: v2
name: cas-ciip-portal
description: A Helm chart for the CIIP portal
type: application
version: 0.1.0
appVersion: 1.0.0-rc.1
dependencies:
- name: cas-postgres
  version: "0.2.0"
  repository: https://bcgov.github.io/cas-postgres/
