apiVersion: v2
name: cas-ciip-portal
description: A Helm chart for the CIIP portal
type: application
version: 0.3.31
appVersion: 2.14.1
dependencies:
  - name: cas-postgres
    version: "0.8.0"
    repository: https://bcgov.github.io/cas-postgres/
  - name: mailhog
    version: "3.3.0"
    repository: "https://codecentric.github.io/helm-charts/"
    condition: mailhog.enable
  - name: cas-airflow-dag-trigger
    version: 1.0.7
    repository: https://bcgov.github.io/cas-airflow
    alias: download-cas-ciip-portal-dags
  - name: cas-airflow-dag-trigger
    version: 1.0.7
    repository: https://bcgov.github.io/cas-airflow
    alias: airflow-ciip-cert-issue
    condition: route.insecure
  - name: cas-airflow-dag-trigger
    version: 1.0.7
    repository: https://bcgov.github.io/cas-airflow
    alias: airflow-ciip-deploy-db
  - name: nginx-sidecar
    repository: https://bcgov.github.io/cas-template-app
    version: 0.1.8
