apiVersion: v2
name: cas-ciip-portal
description: A Helm chart for the CIIP portal
type: application
version: 0.1.20
appVersion: 1.3.0
dependencies:
- name: cas-postgres
  version: "0.5.0"
  repository: https://bcgov.github.io/cas-postgres/
- name: mailhog
  version: "3.2.0"
  repository: "https://codecentric.github.io/helm-charts/"
  condition: mailhog.enable
