apiVersion: v2
name: cas-ciip-portal
description: A Helm chart for the CIIP portal
type: application
version: 0.3.23
appVersion: 2.11.4
dependencies:
  - name: cas-postgres
    version: "0.8.0"
    repository: https://bcgov.github.io/cas-postgres/
  - name: mailhog
    version: "3.3.0"
    repository: "https://codecentric.github.io/helm-charts/"
    condition: mailhog.enable
  - name: cas-airflow-dag-trigger
    version: 1.0.6
    repository: https://bcgov.github.io/cas-airflow
    alias: download-cas-ciip-portal-dags
  - name: cas-airflow-dag-trigger
    version: 1.0.6
    repository: https://bcgov.github.io/cas-airflow
    alias: airflow-ciip-cert-issue
  - name: cas-airflow-dag-trigger
    version: 1.0.6
    repository: https://bcgov.github.io/cas-airflow
    alias: airflow-ciip-deploy-db
