apiVersion: v2
name: cas-ciip-portal
description: A Helm chart for the CIIP portal
type: application
version: 0.1.6
appVersion: 1.0.0-rc.7
dependencies:
- name: cas-postgres
  version: "0.4.0"
  repository: https://bcgov.github.io/cas-postgres/
- name: mailhog
  version: "3.2.0"
  repository: "file://../mailhog"
  condition: mailhog.enable
