replicas: 2
route:
  host: test.ciip.gov.bc.ca
  insecure: false # cert has been issued

env:
  smtpConnectionString: smtp://cas-ciip-portal-mailhog:1025
  senderEmail: BC Climate Action Secretariat <no-reply-dev.cas@gov.bc.ca>
  adminEmail: CIIP Admin, BC Climate Action Secretariat <admin@ciip.test>
  enableDbMocks: true

analytics:
  enable: true

sitewide_notice:
  content: <div class="alert alert-warning">This is the TEST environment. All emails will be sent to <a href="https://cas-mailhog-wksv3k-test.pathfinder.gov.bc.ca">the test inbox</a> instead of the real recipients. Please use <strong>testreporter</strong> for testing instead of creating a new account.</div>

dag:
  # cleanup the test db before deploying to test
  preInitDb: |
    psql<<EOF
      select pg_terminate_backend(pid) from pg_stat_activity where
      -- don't kill my own connection!
      pid <> pg_backend_pid()
      -- don't kill the connections to other databases
      and datname = '$(PORTAL_DATABASE)';
      drop database if exists $(PORTAL_DATABASE);
      drop user if exists $(PORTAL_USER);
      drop user if exists ciip_portal;
      drop user if exists ciip_readonly;
    EOF
  # this airflow dag runs the prod-test-restor cron job instead of the swrs import
  name: "ciip_deploy_db_test"

fider:
  host: https://ciip-portal-09269b-test-feedback.pathfinder.gov.bc.ca/
# TODO move fider template in this repo

restoreFromProd:
  enable: true

mailhog:
  enable: true
  securityContext:
    runAsUser: 1009960000
    fsGroup: 1009960000
    runAsNonRoot: true
  host: cas-mailhog-09269b-test.pathfinder.gov.bc.ca

cas-postgres:
  patroni:
    walE:
      enable: true
      # the GCS bucket name should be {{ namespace }}-{{ gcs.bucketSuffix }}
      gcsBucket: 09269b-test-ciip-backups
      # kubernetesSecret should be gcp-{{ namespace }}-{{ gcs.bucketSuffix }}-service-account-key
      kubernetesSecret: gcp-09269b-test-ciip-backups-service-account-key # pragma: allowlist secret
    # options below are required if walE.enable is true
  namespace: 09269b-test
  gcs:
    bucketSuffix: ciip-backups
