replicas: 2
route:
  host: test.ciip.gov.bc.ca

env:
  smtpConnectionString: smtp://cas-ciip-portal-mailhog:1025
  senderEmail: no-reply-dev.cas@gov.bc.ca
  adminEmail: admin@ciip.test
  enableDbMocks: true

analytics:
  enable: true

dag:
  # cleanup the test db before deploying to test
  preInitDb: |
    psql<<EOF
      select pg_terminate_backend(pid) from pg_stat_activity where
      -- don't kill my own connection!
      pid <> pg_backend_pid()
      -- don't kill the connections to other databases
      and datname = '$(PORTAL_DATABASE)';
      drop database if exists $(PORTAL_DATABASE);
      drop user if exists $(PORTAL_USER);
      drop user if exists ciip_portal;
      drop user if exists ciip_readonly;
    EOF
  # this airflow dag runs the prod-test-restor cron job instead of the swrs import
  name: "ciip_deploy_db_test"

restoreFromProd:
  enable: true

mailhog:
  enable: true
  securityContext:
    runAsUser: 1001660000
    fsGroup: 1001660000
    runAsNonRoot: true
  host: cas-mailhog-test.apps.silver.devops.gov.bc.ca

cas-postgres:
  patroni:
    walE:
      enable: true
      # the GCS bucket name should be {{ namespace }}-{{ gcs.bucketSuffix }}
      gcsBucket: 09269b-test-ciip-backups
      # kubernetesSecret should be gcp-{{ namespace }}-{{ gcs.bucketSuffix }}-service-account-key
      kubernetesSecret: gcp-09269b-test-ciip-backups-service-account-key # pragma: allowlist secret
    # options below are required if walE.enable is true
  namespace: 09269b-test
  gcs:
    bucketSuffix: ciip-backups

download-cas-ciip-portal-dags:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca

airflow-ciip-cert-issue:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca

airflow-ciip-deploy-db:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca

nginx-sidecar:
  hostName: test.ciip.gov.bc.ca

ggircs:
  host: https://cas-ggircs-test.apps.silver.devops.gov.bc.ca/

metabase:
  host: https://cas-metabase-test.apps.silver.devops.gov.bc.ca/
