loadTesting:
  enable: true
  image:
    repository: gcr.io/ggl-cas-storage/cas-ciip-portal-k6
    tag: latest
    pullPolicy: Always

dag:
  enable: true
  name: ggircs_ciip_load_testing_data

env:
  enableDbMocks: true
