replicas: 3
route:
  host: ciip.gov.bc.ca
  insecure: false # cert has been issued

analytics:
  enable: true

cas-postgres:
  patroni:
    replicaCount: 4
    resources:
      limits:
        cpu: 3000m
        memory: 2Gi
      requests:
        cpu: 15m
        memory: 600Mi
    walE:
      enable: true
      # the GCS bucket name should be {{ namespace }}-{{ gcs.bucketSuffix }}
      gcsBucket: 09269b-prod-ciip-backups
      # kubernetesSecret should be gcp-{{ namespace }}-{{ gcs.bucketSuffix }}-service-account-key
      kubernetesSecret: gcp-09269b-prod-ciip-backups-service-account-key # pragma: allowlist secret
    # options below are required if walE.enable is true
  namespace: 09269b-prod
  gcs:
    bucketSuffix: ciip-backups
