
exclude: >
            (?x)^(
                test\.js\.snap$|
                stories\.storyshot$
            )$
repos:
- repo: local
  hooks:
    - id: yarn-format
      name: Fix formatting and lint with XO
      language: script
      files: \.(j|t)sx?$
      entry: ./.bin/format.sh
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-vcs-permalinks
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: .*/tests/.*
# - repo: https://github.com/Yelp/detect-secrets
#   rev: v0.12.7
#   hooks:
#     - id: detect-secrets
#       args: ['--baseline', '.secrets.baseline']
#       exclude: .*/tests/.*
