apiVersion: template.openshift.io/v1
kind: Template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true

objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${PREFIX}portal-app
  spec:
    ports:
    - name: ${PREFIX}portal-app
      nodePort: 0
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      name: ${PREFIX}portal-app
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
