{{- if .Values.networkPolicies.enable }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-intra-release-by-name
  labels: {{ include "cas-ciip-portal.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          release: {{ .Release.Name }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Release.Name }}
{{- end }}
