apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cas-ciip-portal.fullname" . }}-dag-trigger
  labels:
{{ include "cas-ciip-portal.labels" . | indent 4 }}
{{- if .Release.IsUpgrade }}
# This job requires the cas-postgres dependency to be running,
# and is required for the app deployment to become ready.
# Therefore, it needs to be part of the initial install (instead of a pre/post install hook)
# For upgrades, it needs to be a hook so that the delete policy kicks in
# and the previous job template gets deleted (as editing job templates is not allowed)
# It can be a hook during upgrades as the cas-postgres dependency will already be running
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
{{- end }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 1200
  template:
    metadata:
      name: {{ template "cas-ciip-portal.fullname" . }}-dag-trigger
      labels:
{{ include "cas-ciip-portal.labels" . | indent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ template "cas-ciip-portal.fullname" . }}-dag-trigger
        image: {{ .Values.image.schema.repository }}:{{ .Values.image.schema.tag }}
        imagePullPolicy: {{ .Values.image.schema.pullPolicy }}
        env:
          - name: AIRFLOW_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: cas-airflow-admin
          - name: AIRFLOW_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: cas-airflow-admin
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        command:
          - /usr/bin/env
          - bash
          - -c
          - ./trigger-airflow-dag.sh ciip_deploy_db
