apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cas-ciip-portal.fullname" . }}-backup-bucket-provisioner-{{ randAlphaNum 5 | lower }}
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      name: {{ template "cas-ciip-portal.fullname" . }}-backup-bucket-provisioner
      labels: {{ include "cas-ciip-portal.labels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: 1200
      containers:
        - name: bucket-provisioner
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          image: {{ .Values.image.casShelf.repository }}:{{ .Values.image.casShelf.tag }}
          imagePullPolicy: {{ .Values.image.casShelf.pullPolicy }}
          env:
            - name: TFC_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: terraform-cloud-workspace
            - name: TFC_WORKSPACE_ID
              valueFrom:
                secretKeyRef:
                  key: workspace_id
                  name: terraform-cloud-workspace
          command:
            - /usr/bin/env
            - bash
            - -c
            - |
              set -xeuo pipefail;
              /script.sh {{ .Release.Namespace | quote }} ciip-backups;
              /script.sh {{ .Release.Namespace | quote }} ciip-documents;
      restartPolicy: Never
