apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cas-ciip-portal.fullname" . }}
  labels:
    component: app
{{ include "cas-ciip-portal.labels" . | indent 4 }}

spec:
  replicas: {{ .Values.replicas }}
  selector:
    name: {{ template "cas-ciip-portal.fullname" . }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: app
{{ include "cas-ciip-portal.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: app
{{ include "cas-ciip-portal.labels" . | indent 8 }}
    spec:
      initContainers:
      - env:
        - name: SQITCH_TARGET
          value: "db:pg:"
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ template "cas-ciip-portal.fullname" . }}
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ template "cas-ciip-portal.fullname" . }}
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{ template "cas-ciip-portal.fullname" . }}
        - name: PGPORT
          value: "5432"
        - name: PGHOST
          value: {{ template "cas-ciip-portal.fullname" . }}-patroni
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        name: {{ template "cas-ciip-portal.fullname" . }}-wait-for-migrations
        image: {{ .Values.image.schema.repository }}:{{ .Values.image.schema.tag }}
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        command:
          - /usr/bin/env
          - bash
          - -c
          - |
            set -euo pipefail;
            pushd schema;
            while [ "$(sqitch status | tail -1)" != "Nothing to deploy (up-to-date)" ]; do
              echo "Waiting 10s for migrations to complete..."
              sleep 10;
            done;
      containers:
      - name: {{ template "cas-ciip-portal.fullname" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}
        env:
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                key: session-secret
                name: {{ template "cas-ciip-portal.fullname" . }}
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                key: database-app-user
                name: {{ template "cas-ciip-portal.fullname" . }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: database-app-password
                name: {{ template "cas-ciip-portal.fullname" . }}
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: {{ template "cas-ciip-portal.fullname" . }}
          - name: PGPORT
            value: "5432"
          - name: PGHOST
            value: {{ template "cas-ciip-portal.fullname" . }}-patroni
          - name: PORT
            value: {{ .Values.port | quote }}
          - name: SMTP_CONNECTION_STRING
            value: {{ .Values.env.smtpConnectionString }}
          - name: SENDER_EMAIL
            value: {{ .Values.env.senderEmail }}
          - name: ADMIN_EMAIL
            value: {{ .Values.env.adminEmail }}
          - name: SUPPORT_EMAIL
            value: {{ .Values.env.supportEmail }}
          - name: ENABLE_ANALYTICS
            value: {{ .Values.analytics.enable | quote }}
          - name: SITEWIDE_NOTICE
            value: {{ .Values.sitewide_notice.content | quote }}
          - name: HOST
            value: http{{ if not .Values.route.insecure }}s{{ end }}://{{ .Values.route.host }}
          - name: GGIRCS_HOST
            value: {{ .Values.ggircs.host }}
          - name: METABASE_HOST
            value: {{ .Values.metabase.host }}
          - name: SENTRY_ENVIRONMENT
            value: {{ include "cas-ciip-portal.namespaceSuffix" . }}
          - name: SENTRY_RELEASE
            value: {{ .Values.image.app.tag }}
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: ENABLE_DB_MOCKS
            value: {{ .Values.env.enableDbMocks | quote }}
          - name: KC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-gold-client-secret
                key: kcClientSecret
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/attachments-credentials/attachments-credentials.json"
          - name: ATTACHMENTS_BUCKET
            valueFrom:
              secretKeyRef:
                name: gcp-{{ .Release.Namespace }}-ciip-documents-service-account-key
                key: bucket_name
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.probesPort }}
          # we want the readiness threshold to fail fast,
          # to prevent any request from going to a pod that is not ready
          failureThreshold: 1
          successThreshold: 1
          periodSeconds: 5
          timeoutSeconds: 5
          initialDelaySeconds: 5
        livenessProbe:
          # the liveness probe is here to ensure that a pod does not get
          # stuck in a shutdown state. It needs to allow enough time for
          # the registered shutdown handler to run to completion.
          httpGet:
            path: /live
            port: {{ .Values.probesPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - mountPath: "/attachments-credentials"
            name: gcs-documents-credentials
            readOnly: true
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
{{- if (index .Values "nginx-sidecar") }}
{{- include "nginx-sidecar.deployment-container.tpl" (index .Values "nginx-sidecar") | indent 6 }}
{{- end }}
      volumes:
{{- if (index .Values "nginx-sidecar") }}
{{- include "nginx-sidecar.deployment-volumes.tpl" (index .Values "nginx-sidecar") | nindent 8 }}
{{- end }}
        - name: gcs-documents-credentials
          secret:
            secretName: gcp-{{ .Release.Namespace }}-ciip-documents-service-account-key #pragma: allowlist secret
            items:
            - key: credentials.json
              path: attachments-credentials.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
