{{- if .Values.restoreFromProd.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cas-ciip-portal.fullname" . }}-prod-restore
  labels:
{{ include "cas-ciip-portal.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-upgrade,pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-5"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: netapp-block-standard
{{- end }}
