apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cas-ciip-portal.fullname" . }}
  labels:
{{ include "cas-ciip-portal.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  session-secret: {{ randAlphaNum 32 | b64enc | quote }}
  database-name: {{ .Values.persistence.db | b64enc | quote }}
  database-user: {{ .Values.persistence.dbOwner | b64enc | quote }}
  database-password: {{ randAlphaNum 32 | b64enc | quote }}
  database-app-user: {{ .Values.persistence.appUser | b64enc | quote }}
  database-app-password: {{ randAlphaNum 32 | b64enc | quote }}
  database-readonly-user: {{ .Values.persistence.readonlyUser | b64enc | quote }}
  database-readonly-password: {{ randAlphaNum 32 | b64enc | quote }}
