version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/postgres:11.4
    steps:
      - checkout
      - run: yarn
      - run: yarn test
workflows:
  version: 2
  test:
    jobs:
      - test
