name: "Set up CIIP dev environment"
description: "Sets up asdf, perl, and configures the cache"
runs:
  using: composite
  steps:
    - name: asdf setup
      uses: asdf-vm/actions/setup@v3
    - name: install pg perl library
      run: sudo apt-get install -y perl libpq-dev libdbd-pg-perl
      shell: bash
    - name: set perl env variables
      shell: bash
      run: | # pragma: allowlist secret
        echo "PERL5LIB=/home/runner/perl5/lib/perl5" >> $GITHUB_ENV
        echo "PERL_LOCAL_LIB_ROOT=/home/runner/perl5" >> $GITHUB_ENV
        echo "PERL_MB_OPT=--install_base '/home/runner/perl5'" >> $GITHUB_ENV
        echo "PERL_MM_OPT=INSTALL_BASE=/home/runner/perl5" >> $GITHUB_ENV
        echo "/home/runner/perl5/bin" >> $GITHUB_PATH
        echo "CURRENT_PERL_VERSION=$(perl -e 'print "$^V\n"')" >> $GITHUB_ENV
    - uses: actions/cache@v4
      id: asdf-cache
      with:
        path: |
          ~/.asdf
        key: ${{ runner.os }}-asdf-cache-${{ hashFiles('.tool-versions') }}
    - uses: actions/cache@v4
      id: perl-cache
      with:
        path: |
          ~/perl5
        key: ${{ runner.os }}-perl-cache-${{ env.CURRENT_PERL_VERSION }}-${{ hashFiles('cpanfile') }}
    - uses: actions/cache@v4
      id: yarn-cache
      with:
        path: |
          ~/.cache/yarn
          ~/.cache/Cypress
          ./app/node_modules
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('app/yarn.lock') }}-v2
    - name: update submodules
      run: git submodule update --init
      shell: bash
