
route:
  host: ~
  insecure: true

nginx-sidecar:
  image:
    repository: ghcr.io/bcgov/cas-nginx
    tag: 0.1.16
    pullPolicy: Always
  objectNamePrefix: cas-ciip-portal-static
  hostName: dev.ciip.gov.bc.ca
  port: 3001
  internalPort: 3000
  sslTermination: false
  caServerSecret: ~ # pragma: allowlist secret
  caServerKey: https://acme-staging-v02.api.letsencrypt.org/directory
  caAccountEmail: ggircs@gov.bc.ca
  storageClassName: netapp-file-standard
  renewalDays: 60
  clientMaxBodySize: 50M
