{{- if .Values.loadTesting.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cas-ciip-portal.fullname" . }}-load-testing
  labels: {{ include "cas-ciip-portal.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-upgrade,post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ template "cas-ciip-portal.fullname" . }}-load-testing
      labels: {{ include "cas-ciip-portal.labels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: 3600
      restartPolicy: Never
      containers:
      - name: {{ template "cas-ciip-portal.fullname" . }}-dag-k6
        image: {{ .Values.loadTesting.image.repository }}:{{ .Values.loadTesting.image.tag }}
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
          requests:
            cpu: '2'
            memory: 1Gi
        imagePullPolicy: {{ .Values.loadTesting.image.pullPolicy }}
        env:
          - name: PERF_MODE
            value: load
          - name: GRAPHQL_ENDPOINT
            value: https://{{ .Values.route.host }}/graphql
{{- end }}
