{{- /*
These template are meant to be injected inside a deployment object, as an additional container
*/}}

{{- define "nginx-sidecar-lib.deployment-container.tpl" -}}
- name: {{ .Chart.Name }}-nginx
  image: "{{ .Values.nginxSidecar.image.repository }}:{{ .Values.nginxSidecar.image.tag }}"
  imagePullPolicy: {{ .Values.nginxSidecar.image.pullPolicy }}
  ports:
    - containerPort: {{ .Values.nginxSidecar.port }}
  volumeMounts:
    - name: nginx-configs
      mountPath: /etc/nginx/conf.d
{{ include "nginx-sidecar-lib.deployment-mounts.tpl" . | indent 4 }}
{{- end -}}


{{- define "nginx-sidecar-lib.deployment-mounts.tpl" -}}
- mountPath: /home/.acme.sh
  name: acme-home
- mountPath: /home/.well-known/acme-challenge
  name: acme-challenge
{{- end -}}


{{- define "nginx-sidecar-lib.deployment-volumes.tpl" -}}
- name: acme-home
  persistentVolumeClaim:
    claimName: {{ template "nginx-sidecar-lib.fullname" . }}-acme-home
- name: acme-challenge
  persistentVolumeClaim:
    claimName: {{ template "nginx-sidecar-lib.fullname" . }}-acme-challenge
{{- end -}}
