{{- $caServer := "https://acme-v02.api.letsencrypt.org/directory" }}

{{- if .Values.caServerSecret }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.caServerSecret ) }}
{{- $caServer = (index $secret.data .Values.caServerKey) | b64dec }}
{{- end -}}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "nginx-sidecar-lib.fullname" . }}-acme-renewal
  labels:
{{ include "nginx-sidecar-lib.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-upgrade,post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-5"

spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
{{ include "nginx-sidecar-lib.labels" . | indent 14 }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ template "nginx-sidecar-lib.fullname" . }}-acme-renewal
              image: bitnami/git
              pullPolicy: Always
              resources:
                limits:
                  cpu: 1000m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
              command:
                - /usr/bin/env
                - bash
                - -c
                - |
                  set -euxo pipefail;
                  # renews the certificate if needed
                  /root/.acme.sh/acme.sh --cron --home /root/.acme.sh --server {{ $caServer }} --days {{.Values.renewalDays}};
              volumeMounts: {{ include "nginx-sidecar-lib.deployment-mounts.tpl" . | nindent 16 }}
          volumes: {{ include "nginx-sidecar-lib.deployment-volumes.tpl" . | nindent 12 }}
