apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: job-template


parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true
- description: Openshift project name
  displayName: Project
  name: OC_PROJECT
  required: true
- description: Openshift registry URL
  displayName: Registry
  name: OC_REGISTRY
  required: true

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${PREFIX}ciip-portal-data-deploy
  spec:
    backoffLimit: 0
    activeDeadlineSeconds: 120
    template:
      metadata:
        labels:
          name: ${PREFIX}ciip-portal-data-deploy
      spec:
        restartPolicy: Never
        containers:
        - command:
          - /usr/bin/env
          - bash
          - -c
          - |
            ./data/deploy-test-data.sh;
          env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${PREFIX}ggircs-postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${PREFIX}ggircs-postgres
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: ${PREFIX}ggircs-postgres
          - name: PGPORT
            value: "5432"
          - name: PGHOST
            value: ${PREFIX}postgres-master
          image: ${OC_REGISTRY}/${OC_PROJECT}/${PREFIX}postgres:${master}
          name: ${PREFIX}ciip-portal-data-deploy
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
