apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: job-template


parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true
- description: Openshift project name
  displayName: Project
  name: OC_PROJECT
  required: true
- description: Openshift registry URL
  displayName: Registry
  name: OC_REGISTRY
  required: true

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${PREFIX}ciip-2018-schema-revert
  spec:
    backoffLimit: 0
    activeDeadlineSeconds: 120
    template:
      metadata:
        labels:
          name: ${PREFIX}ciip-2018-schema-revert
      spec:
        restartPolicy: Never
        containers:
        - command:
          - /usr/bin/env
          - bash
          - -c
          - |
            sqitch revert @v1.0.0 -y;
          env:
          - name: SQITCH_TARGET
            value: "db:pg:"
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${PREFIX}postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${PREFIX}postgres
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: ${PREFIX}postgres
          - name: PGPORT
            value: "5432"
          - name: PGHOST
            value: ${PREFIX}postgres
          - name: SQITCH_FULLNAME
            value: OpenShift Deployer
          - name: SQITCH_EMAIL
            value: deployer@pathfinder.gov.bc.ca
          image: ${OC_REGISTRY}/${OC_PROJECT}/${PREFIX}ciip-2018-schema:${GIT_SHA1}
          name: ${PREFIX}ciip-2018-schema-revert
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
