apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: job-template


parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true
- description: Openshift project name
  displayName: Project
  name: OC_PROJECT
  required: true
- description: Openshift registry URL
  displayName: Registry
  name: OC_REGISTRY
  required: true

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${PREFIX}portal-schema-revert
  spec:
    backoffLimit: 0
    activeDeadlineSeconds: 7200
    template:
      metadata:
        labels:
          name: ${PREFIX}portal-schema-revert
      spec:
        restartPolicy: Never
        containers:
        # TODO: revert to a release to avoid deleting all the data
        - command:
          - /usr/bin/env
          - bash
          - -c
          - sqitch revert -y
          env:
          - name: SQITCH_TARGET
            value: "db:pg:"
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${PREFIX}portal-postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${PREFIX}portal-postgres
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: ${PREFIX}portal-postgres
          - name: PGPORT
            value: "5432"
          - name: PGHOST
            value: ${PREFIX}postgres-master
          - name: SQITCH_FULLNAME
            value: OpenShift Deployer
          - name: SQITCH_EMAIL
            value: deployer@pathfinder.gov.bc.ca
          image: ${OC_REGISTRY}/${OC_PROJECT}/${PREFIX}portal-schema:${GIT_SHA1}
          name: ${PREFIX}portal-schema-revert
          resources:
            limits:
              cpu: "1"
              memory: 64Mi
            requests:
              cpu: 500m
              memory: 64Mi
