apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cas-ciip-portal-static.fullname" . }}-ciip-static
  labels: {{ include "cas-ciip-portal-static.labels" . | nindent 4 }}
data:
  ciip-static.html: |
    <!DOCTYPE html>
    <html>
    <body>

    <h1>CIIIIIIIIIIP</h1>

    </body>
    </html>
