apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cas-ciip-portal-static.fullname" . }}
  labels:
{{- include "cas-ciip-portal-static.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- include "cas-ciip-portal-static.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{- include "cas-ciip-portal-static.labels" . | nindent 8 }}
    spec:
      containers:
{{- if (index .Values "nginx-sidecar") }}
{{- include "nginx-sidecar.deployment-container.tpl" (index .Values "nginx-sidecar") | indent 8 }}
{{- end }}
        - name: {{ .Release.Name }}
          image: ghcr.io/bcgov/cas-nginx:1.29.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            failureThreshold: 1
            successThreshold: 1
            periodSeconds: 30
            timeoutSeconds: 5
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /liveness
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: ciip-static
              mountPath: /www/data
      restartPolicy: Always
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "cas-ciip-portal-static.fullname" . }}-nginx-config
        - name: ciip-static
          configMap:
            name: {{ include "cas-ciip-portal-static.fullname" . }}-ciip-static
{{- if (index .Values "nginx-sidecar") }}
{{- include "nginx-sidecar.deployment-volumes.tpl" (index .Values "nginx-sidecar") | indent 8 }}
{{- end }}
