kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-intra-release-by-name
  labels: {{ include "cas-ciip-portal-static.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cas-ciip-portal-static.name" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "cas-ciip-portal-static.name" . }}
