apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cas-ciip-portal-static.fullname" . }}-nginx-config
  labels: {{ include "cas-ciip-portal-static.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 3000;

      root /www/data;

      location / {
        index ciip-static.html;
      }

      location /readiness {
        return 200;
      }

      location /liveness {
        return 200;
      }

    }
