apiVersion: v1
kind: Service
metadata:
  name: {{ include "cas-ciip-portal-static.fullname" . }}
  labels:
{{ include "cas-ciip-portal-static.labels" . | indent 4 }}
spec:
  ports:
  - name: {{ template "cas-ciip-portal-static.fullname" . }}
    port: 3000
    protocol: TCP
    targetPort: 3001
  selector:
{{ include "cas-ciip-portal-static.selectorLabels" . | indent 4 }}
  sessionAffinity: None
  type: ClusterIP
