
{{- $caServer := "https://acme-v02.api.letsencrypt.org/directory" }}

{{- if .Values.caServerSecret }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.caServerSecret ) }}
{{- $caServer = (index $secret.data .Values.caServerKey) | b64dec }}
{{- end -}}


apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.objectNamePrefix }}-acme-issue
  labels:
{{ include "nginx-sidecar.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-upgrade,post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-5"
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
{{ include "nginx-sidecar.labels" . | indent 14 }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Values.objectNamePrefix }}-acme-issue
              image: bitnami/git
              resources:
                limits:
                  cpu: 1000m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
              command:
                - /usr/bin/env
                - bash
                - -c
                - |
                  set -euxo pipefail;
                  if [ ! -f /root/.acme.sh/{{ .Values.hostName }}/{{ .Values.hostName }}.cer ]; then
                    echo "Getting a new cert from Let's Encrypt for {{ .Values.hostName }}";
                    git clone --branch 2.8.6 https://github.com/acmesh-official/acme.sh.git /root/acme.sh;
                    cd /root/acme.sh;
                    ./acme.sh install --force --server {{ $caServer }} -m {{ .Values.caAccountEmail }} ;
                    . "/root/.acme.sh/acme.sh.env";
                    ./acme.sh --issue -d {{ .Values.hostName }} -w /root --server {{ $caServer }} -m {{ .Values.caAccountEmail }} --days {{.Values.renewalDays}};
                  fi;
              volumeMounts: {{ include "nginx-sidecar.deployment-mounts.tpl" . | nindent 16 }}
          volumes: {{- include "nginx-sidecar.deployment-volumes-pvcs.tpl" .Values | nindent 12 }}
