{{- $caServer := "https://acme-v02.api.letsencrypt.org/directory" }}

{{- if .Values.caServerSecret }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.caServerSecret ) }}
{{- $caServer = (index $secret.data .Values.caServerKey) | b64dec }}
{{- end -}}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.objectNamePrefix }}-acme-renewal
  labels:
{{ include "nginx-sidecar.labels" . | indent 4 }}
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
{{ include "nginx-sidecar.labels" . | indent 14 }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Values.objectNamePrefix }}-acme-renewal
              image: bitnami/git
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 1000m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
              command:
                - /usr/bin/env
                - bash
                - -c
                - |
                  set -euxo pipefail;
                  # renews the certificate if needed
                  /tmp/.acme.sh/acme.sh --cron --home /tmp/.acme.sh --server {{ $caServer }} --days {{.Values.renewalDays}};
              volumeMounts:
                - mountPath: /tmp/.acme.sh
                  name: acme-home
                - mountPath: /tmp/.well-known/acme-challenge
                  name: acme-challenge
          volumes: {{ include "nginx-sidecar.deployment-volumes-pvcs.tpl" .Values | nindent 12 }}
          imagePullSecrets:
            - name: dockerhub-registry
