{{- if .Values.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "nginx-sidecar.fullname" . }}-acme-challenge
  labels: {{ include "nginx-sidecar.labels" . | nindent 4 }}

spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 25Mi
  storageClassName: {{ .Values.storageClassName }}
{{- end }}
