apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true
- description: Openshift project name
  displayName: Project
  name: OC_PROJECT
  required: true
- description: Openshift registry URL
  displayName: Registry
  name: OC_REGISTRY
  required: true

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${PREFIX}portal-app
  spec:
    replicas: 2
    selector:
      name: ${PREFIX}portal-app
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${PREFIX}portal-app
      spec:
        containers:
        - env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                key: database-app-user
                name: ${PREFIX}portal-postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: database-app-password
                name: ${PREFIX}portal-postgres
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: ${PREFIX}portal-postgres
          - name: PGPORT
            value: "5432"
          - name: PGHOST
            value: ${PREFIX}postgres-master
          - name: PORT
            value: "3000"
          - name: SMTP_CONNECTION_STRING
            value: smtp://apps.smtp.gov.bc.ca/?port=25&ignoreTLS=true&secure=false
          - name: SENDER_EMAIL
            value: no-reply.cas@gov.bc.ca
          - name: FEEDBACK_SITE_URL
            value: https://ciip-portal-${OC_PROJECT}-feedback.pathfinder.gov.bc.ca
          - name: HOST
            value: https://ciip-portal-${OC_PROJECT}.pathfinder.gov.bc.ca
          - name: PROJECT
            value: ${OC_PROJECT}

          image: ${OC_REGISTRY}/${OC_PROJECT}/${PREFIX}portal-app:${GIT_SHA1}
          imagePullPolicy: IfNotPresent
          name: ${PREFIX}portal-app
          ports:
          - containerPort: 3000
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
