apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true
  - description: Base64-encoded portal DB.
    displayName: Portal DB
    name: PORTAL_DB
    required: true
  - description: Base64-encoded ggircs user.
    displayName: Giircs user
    name: PORTAL_USER
    required: true
  - description: Base64-encoded password for the ggircs user.
    displayName: Giircs Password
    name: PORTAL_PASSWORD
    required: true
  - description: Base64-encoded portal app user.
    displayName: Giircs read-only user
    name: PORTAL_APP_USER
    required: true
  - description: Base64-encoded password for the portal app user.
    displayName: Giircs Password
    name: PORTAL_APP_PASSWORD
    required: true

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        beta.kubernetes.io/os: linux
      name: ${PREFIX}portal-postgres
    type: Opaque
    data:
      database-name: ${PORTAL_DB}
      database-user: ${PORTAL_USER}
      database-password: ${PORTAL_PASSWORD}
      database-app-user: ${PORTAL_APP_USER}
      database-app-password: ${PORTAL_APP_PASSWORD}
