{{- if .Values.networkSecurityPolicies.enable }}
kind: NetworkSecurityPolicy
apiVersion: security.devops.gov.bc.ca/v1alpha1
metadata:
  name: {{ .Release.Name }}-intra-release
  labels:
{{ include "cas-ciip-portal.labels" . | nindent 4 }}
spec:
  description: allow everything within this release to communicate
  source:
    - - $namespace={{ .Release.Namespace }}
      - release={{ .Release.Name }}
  destination:
    - - $namespace={{ .Release.Namespace }}
      - release={{ .Release.Name }}
{{- end }}
