apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cas-ciip-portal-data-migrate.fullname" . }}
  labels: {{ include "cas-ciip-portal-data-migrate.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClass }}
