enable: false
image:
  repository: gcr.io/ggl-cas-storage/cas-nginx
  tag: latest
  pullPolicy: Always
# set to false to deploy the application with an insecure route,
# and issue an SSL certificate using acme.sh
sslTermination: true
# If provided, the acme issue/renewal scripts will use a custom server
# Otherwise it defaults to Let's Encrypt
caServerSecret: ~ #pragma: allowlist secret
caServerKey: ~
caAccountEmail: ggircs@gov.bc.ca
storageClassName: netapp-file-standard
renewalDays: 60
certTargetHost: "example-climate-action-secretariat.gov.bc.ca"
