-- Revert ggircs-portal:policies/ciip_user_organisation_policies_002_recreate_after_type_change from pg

begin;

drop policy ciip_industry_user_select_ciip_user_organisation on ggircs_portal.ciip_user_organisation;
drop policy ciip_industry_user_insert_ciip_user_organisation on ggircs_portal.ciip_user_organisation;

commit;
